server {
        listen 80 default_server;
        server_name localhost;

        root /var/www/emagine.com.br/home;
        index index.html;

        location / {
                try_files $uri $uri/ /index.html;
                error_page 404 403 /index.html;
        }

        location = /nauth {
                return 301 /nauth/;
        }

        location ^~ /nauth/ {
                alias /var/www/emagine.com.br/nauth/;
                index index.html;
                try_files $uri $uri/ /index.html;
        }

        location = /goblinwars {
                return 301 /goblinwars/;
        }

        location ^~ /goblinwars/ {
                alias /var/www/goblinwars.net/home/;
                index index.html;
                try_files $uri $uri/ /index.html;
        }

        location = /monexup {
                return 301 /monexup/;
        }

        location ^~ /monexup/ {
                alias /var/www/monexup.com/home/;
                index index.html;
                try_files $uri $uri/ /index.html;
        }

        location = /easysla {
                return 301 /easysla/;
        }

        location ^~ /easysla/ {
                alias /var/www/easysla.com/home/;
                index index.html;
                try_files $uri $uri/ /index.html;
        }

        location = /easysla-app {
                return 301 /easysla-app/;
        }

        location ^~ /easysla-app/ {
                alias /var/www/easysla.com/app/;
                index index.html;
                try_files $uri $uri/ /index.html;
        }

        location = /nochainswap {
                return 301 /nochainswap/;
        }

        location ^~ /nochainswap/ {
                alias /var/www/nochainswap.org/home/;
                index index.html;
                try_files $uri $uri/ /index.html;
        }

        location = /pandoravault {
                return 301 /pandoravault/;
        }

        location ^~ /pandoravault/ {
                alias /var/www/pandoravault.com/home/;
                index index.html;
                try_files $uri $uri/ /index.html;
        }

        location = /bazzuca {
                return 301 /bazzuca/;
        }

        location ^~ /bazzuca/ {
                alias /var/www/bazzuca.media/home/;
                index index.html;
                try_files $uri $uri/ /index.html;
        }
}
